### ISSUE TITLE
problem with pos64staker

### ISSUE THREAD

**Issue by Kryonox** [KMDLabs/pos64staker#10]
Hi I have some issues with the pos64staker
I am using the THC chain on Komodo
I always keep getting this error
___________________________________

configuration as follows
1. Main THC wallet on an Intel NUC Core i7 minipc running Ubuntu 18.04 64
2. Windows 7 64 pc running VirtualBox / Ubuntu 18.04 64 for a Test Wallet THC
____________________________________

Can I start with the smallest problem wich is allready resolved.
On the Windows/VirtualBox/Ubuntu, after having so many problems on Intel Nuc / Main Wallet,
I put 100 THC run the ./TUIstaker script and got the following output error:

amont UTXO = 4
done
percentage = 5
pfff
make a selection:2
Balance: 100.0
Please specify the amount of UTXOs to send to each segid: 4
Total number of UTXOs: 256
Average utxo size: 0.390625
Enter percentage of variance: 5
Cant stake coin amounts less than 1 coin, try again.
Please specify the amount of UTXOs to send to each segid
Seemed clear, so I put 1.000THC. Rerun script .... everything seemed to work. The amount of 1000THC got split and matured and so .... Good

Their seems to be a minimum of coins necessary to run the pos64staker script

______________________________________

Now, the main problem
On the Intel Nuc / Ubuntu / Main Wallet I have 126.000 THC
but after running ./TUIstaker.py script and entering the values us provides through a tutorial,
I always got the same error message:
-account has insuficiant amount. - Please use [8] unlock coins. (which I did, coins unlocked ... no difference).
I tried a lot of combinations utxo/variance. Nothing seems to work.

I also see that my Min size and Max size are very high.
And when I calculate: (Total nr UTXO x Avg utxo size) that gives exact amount in balance. 256 x 518,67 =
But when I calculate: (Total nr UTXO x Max utxo size) that gives more then amount in balance. 256 x 518,67 = 132.830,72

Whatever inputs I give for UXTo or variance, I got always the same error

some outputs

make a selection: <2>
Balance: 126506.269273
Please specify the amount of UTXOs to send to each segid:  <4>
Total number of UTXOs: 256
Average utxo size: 494.16511434765624
Enter percentage of variance:  <5>
Min size: 469.46
Max size: 518.87
Are you happy with these?(y/n):

make a selection: <2>
Balance: 126506.269273
Please specify the amount of UTXOs to send to each segid:  <4>
Total number of UTXOs: 256
Average utxo size: 494.16511434765624
Enter percentage of variance:  <1>
Min size: 489.22
Max size: 499.11
Are you happy with these?(y/n):

so whatever I put in I still come with a value higher then my account amount
even when I put percentage of variance to 0 (zero), I still have 126507 (1 THC too high)
and when I chose percentage of variance at zero, after typing 'happy? - y' then the script get blocked on : please wait .... (I waited a very very long time)
And this also made that Intel NUC working at 100% including fan speed.

![VdIyJemUDB](https://user-images.githubusercontent.com/53604038/62361741-e0b1bd80-b51b-11e9-81a1-0a2a7c89fc9f.png)

I left it that way - all night - in the morning still same screenshot
so ... I typed ctrl /c with following screenshot

![Hllnf8NUmJ](https://user-images.githubusercontent.com/53604038/62361777-f9ba6e80-b51b-11e9-8dd3-4a5a4d5a8723.png)

So, then I tried option 1: sendmany64
the parameters are then chosen so that I stay below my total amount.
still I get an error as follows:

Some outputs

make a selection: <1>
Balance: 126509.869423
Please specify the size of UTXOs:  <245>
Please specify the amount of UTXOs to send to each segid: <8>
Total amount: 125440.0
Traceback (most recent call last):
  File "./TUIstaker.py", line 318, in <module>
    select_loop('')
  File "./TUIstaker.py", line 117, in select_loop
    chain_loop(chain, '')
  File "./TUIstaker.py", line 139, in chain_loop
    msg = stakerlib.sendmany64_TUI(chain, rpc_connection)
  File "/home/user/pos64staker/stakerlib.py", line 250, in sendmany64_TUI
    sendmanyloop_result = sendmanyloop(rpc_connection, AMOUNT, UTXOS)
  File "/home/user/pos64staker/stakerlib.py", line 212, in sendmanyloop
    sendmany64_txid = sendmany64(rpc_connection, amount, 0)
TypeError: sendmany64() takes 2 positional arguments but 3 were given
with at the end some errors ...

and a screenshot from another attempt

![SEmKhnS3KS](https://user-images.githubusercontent.com/53604038/62361807-0b037b00-b51c-11e9-8d1c-c1a5f8863d07.png)

seems there is a min and max amount of coins needed ...?

But as I didn't know about this channel, I allready have reinstalled the 'Intel NUC / Ubuntu / Main THC Wallet' and put (for the moment) only 1000THC on it.
 
could you advise please

Thank you

**Comment by Alrighttt** [comment]
Hello, thanks for the feedback. Yes, there is an arbitrary limitation in the splitter of 64*3 coins. I will work on removing this. 

Is the "please wait..." hanging bug easily reproducible? If you could explain how I can reproduce this on my end, it would help. If I can't do it on my end, but you can consistently make it happen on your node, I will add some debug prints to get a sense of what it's getting stuck doing. 

When I rewrite the splitter function, I'll need you to test the insufficient funds thing again. May fix itself when I do the rewrite. 

I'll try to get to this week.

**Comment by Kryonox** [comment]
Hi thank you for your answer.
- But how can I interpret that limitation of 64*3 coins in relation to max amount of UTXO's per segID or the average/max UTXO size? Or in relation to the max amount of coins possible to pos64stake?

Is 64*3=192coins the max UTXO size then? So, that would be 192 * amount UTXO / segID * 64 and that must be smaller then the balance amount?

- But what I found weird is, that whatever I tried (when I had 125.000 THC) the average UTXO size * max UTXO equals my balance amount exactly. But still the TUIstaker script would not accept the values ...
 
- Since I didn't know about this channel of support, I moved my coins to another wallet, reinstalled everything on Main Wallet, send only 50K THC coins to Main wallet. And with max UTXO/segID=8 and variance=5 all seems to work well.
So, I cannot reproduce that "please wait ..." , which I had when putting variance=0.
Sorry  for that. But I can give it a try on the other wallet, with still about 76K coins in it, which is running on Windows7 with VirtualBox/Ubuntu 18.04.

- So, for now I leave this Main wallet with 50K THC running for 24h and think of sending the rest of the coins to it.
Or should that give problems? Perhaps I should restart TUIstaker then?
Thank you

**Comment by Kryonox** [comment]
Now, i've tried the same procedure as I did above, with the remaining 76K THC coins on VirtualBox/Ubuntu.
same errors "Error: sendmany command failed with sendmany: Account has insufficient funds (code -6) Please use [8 | unlock all locked utxos] then try again"
with sendmany64 .... I see some error lines coming from TUIstaker
![sendmany](https://user-images.githubusercontent.com/53604038/62395989-26997080-b572-11e9-8f8d-eb5419f585b7.png)

**Comment by Kryonox** [comment]
so .. I can reproduce the "Please wait ... " hanging bug.

I made sure all coins (76564,605306 THC) were in one validated address on VirtualBox/Ubuntu.

amount UXTO=0 to 16 and  variance=0 gives error message 
(Error: sendmany command failed with sendmany: Account has insufficient funds (code -6)
Please use [8 | unlock all locked utxos] then try again)

amount UTXO: 17 or greater and variance=0 gives hanging bug

Hoping this is of some help for you

**Comment by Kryonox** [comment]
I finally got it working with full amount of coins ..
not really sure how, and even less what the problem could be
hate that, nothing learned
I tried different things in different VirtualBoxes/ Ubuntu
... seems to work now, whatever the problem was

**Comment by smk762** [comment]
try running `tail -f ~/.komodo/THC/debug.log` in a separate window while doing the above, it might reveal some clues

**Comment by Kryonox** [comment]
Thx smk762 ... but I finally got it working now with full amount.
debug.log should be without errors then?

**Comment by smk762** [comment]
It might display ignorable errors for things like orphaned blocks or bad peers
